name = "Advanced Interactive Devices"
prefix = "aid"
mainprefix = "z"

[hemtt.launch]
workshop = [
    "450814997", # CBA
    "751965892", # ACRE2
    "463939057", # ACE3
    "1779063631", # Zeus Enhanced
    "2018593688", # Zeus Enhanced ACE3 Compatibility
]
