name = "Advanced Interactive Devices"
prefix = "aid"
mainprefix = "z"

[files]
include = [
    "aid_x64.dll",
    "aid.dll",
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA
    "751965892", # ACRE2
    "463939057", # ACE3
    "1779063631", # Zeus Enhance
]
mission = "2_riflemen.Stratis"
