name = "Advanced Interactive Devices"
prefix = "aid"
mainprefix = "z"

[files]
include = [
    "aid_x64.dll",
    "aid.dll",
]

[hemtt.launch.default]
workshop = [
    "450814997", # CBA
    "751965892", # ACRE2
    "463939057", # ACE3
    "1779063631", # Zeus Enhanced
]
mission = "2_riflemen.Stratis"

[hemtt.launch.adt]
extends = "default"
workshop = [
    "3499977893", # ADT
]

[hemtt.launch.profile]
extends = "default"
workshop = [
    "1652506957", # Arma Script Profiler
    "1645973522", # Intercept
]
