name: arma

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - uses: Swatinem/rust-cache@v1
        with:
          key: arma

      - name: Build Extension
        run: |
          cargo build --release
          cp target/release/aid.dll aid_x64.dll

      - name: Build Mod
        run: hemtt build

      - name: Rename build folder
        run: mv .hemttout/build .hemttout/@aid

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: aid.zip
          path: .hemttout/@*
          include-hidden-files: true 
