name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1

      - name: Install latest Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true

      - name: Cargo Build
        run: cargo build --release

      - name: Copy DLL
        run: |
          copy target\release\aid.dll aid_x64.dll

      - name: Build Mod
        run: hemtt release

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: aid.zip
          path: releases/aid-latest.zip
